<?php
use Illuminate\Database\Seeder;

class VehicleModelsSeeder extends Seeder
{

    public function run()
    {
        DB::table('vehicle_models')->insert([
            ['brand_id' => "1", 'name' => '124 Spider'],
            ['brand_id' => "1", 'name' => '500'],
            ['brand_id' => "1", 'name' => '500C'],
            ['brand_id' => "1", 'name' => '595'],
            ['brand_id' => "1", 'name' => '595C'],
            ['brand_id' => "1", 'name' => '595 Competizione'],
            ['brand_id' => "1", 'name' => '595 Turismo'],
            ['brand_id' => "1", 'name' => '695'],
            ['brand_id' => "1", 'name' => '695C'],
            ['brand_id' => "1", 'name' => 'Grande Punto'],
            ['brand_id' => "1", 'name' => 'Punto EVO'],
            ['brand_id' => "1", 'name' => 'Punto Supersport'],

            ['brand_id' => "2", 'name' => '145'],
            ['brand_id' => "2", 'name' => '146'],
            ['brand_id' => "2", 'name' => '147'],
            ['brand_id' => "2", 'name' => '155'],
            ['brand_id' => "2", 'name' => '156'],
            ['brand_id' => "2", 'name' => '159'],
            ['brand_id' => "2", 'name' => '164'],
            ['brand_id' => "2", 'name' => '166'],
            ['brand_id' => "2", 'name' => '1750'],
            ['brand_id' => "2", 'name' => '2000'],
            ['brand_id' => "2", 'name' => '33'],
            ['brand_id' => "2", 'name' => '4C'],
            ['brand_id' => "2", 'name' => '75'],
            ['brand_id' => "2", 'name' => '8C'],
            ['brand_id' => "2", 'name' => '90'],
            ['brand_id' => "2", 'name' => 'Alfa 6'],
            ['brand_id' => "2", 'name' => 'Alfasud'],
            ['brand_id' => "2", 'name' => 'Alfetta'],
            ['brand_id' => "2", 'name' => 'Brera'],
            ['brand_id' => "2", 'name' => 'Crosswagon'],
            ['brand_id' => "2", 'name' => 'Giulia'],
            ['brand_id' => "2", 'name' => 'Giulietta'],
            ['brand_id' => "2", 'name' => 'GT'],
            ['brand_id' => "2", 'name' => 'GTV'],
            ['brand_id' => "2", 'name' => 'MiTo'],
            ['brand_id' => "2", 'name' => 'RZ'],
            ['brand_id' => "2", 'name' => 'Spider'],
            ['brand_id' => "2", 'name' => 'Sportwagon'],
            ['brand_id' => "2", 'name' => 'Sprint'],
            ['brand_id' => "2", 'name' => 'SZ'],

            ['brand_id' => "3", 'name' => "AR1"],
            ['brand_id' => "3", 'name' => "Cygnet"],
            ['brand_id' => "3", 'name' => "DB"],
            ['brand_id' => "3", 'name' => "DB11"],
            ['brand_id' => "3", 'name' => "DB7"],
            ['brand_id' => "3", 'name' => "DB9"],
            ['brand_id' => "3", 'name' => "DBS"],
            ['brand_id' => "3", 'name' => "Lagonda"],
            ['brand_id' => "3", 'name' => "Rapide"],
            ['brand_id' => "3", 'name' => "V12 Vanquish"],
            ['brand_id' => "3", 'name' => "V8"],
            ['brand_id' => "3", 'name' => "Vantage"],
            ['brand_id' => "3", 'name' => "Virage"],
            ['brand_id' => "3", 'name' => "Volante"],

            ['brand_id' => "4", 'name' => "100"],
            ['brand_id' => "4", 'name' => "80"],
            ['brand_id' => "4", 'name' => "A1"],
            ['brand_id' => "4", 'name' => "A2"],
            ['brand_id' => "4", 'name' => "A3"],
            ['brand_id' => "4", 'name' => "A4"],
            ['brand_id' => "4", 'name' => "A4 Allroad"],
            ['brand_id' => "4", 'name' => "A5"],
            ['brand_id' => "4", 'name' => "A6"],
            ['brand_id' => "4", 'name' => "A6 Allroad"],
            ['brand_id' => "4", 'name' => "A7"],
            ['brand_id' => "4", 'name' => "A8"],
            ['brand_id' => "4", 'name' => "Q2"],
            ['brand_id' => "4", 'name' => "Q3"],
            ['brand_id' => "4", 'name' => "Q5"],
            ['brand_id' => "4", 'name' => "Q7"],
            ['brand_id' => "4", 'name' => "R8"],
            ['brand_id' => "4", 'name' => "RS3"],
            ['brand_id' => "4", 'name' => "RS4"],
            ['brand_id' => "4", 'name' => "RS5"],
            ['brand_id' => "4", 'name' => "RS6"],
            ['brand_id' => "4", 'name' => "S1"],
            ['brand_id' => "4", 'name' => "S3"],
            ['brand_id' => "4", 'name' => "S4"],
            ['brand_id' => "4", 'name' => "S5"],
            ['brand_id' => "4", 'name' => "S6"],
            ['brand_id' => "4", 'name' => "S8"],
            ['brand_id' => "4", 'name' => "SQ5"],
            ['brand_id' => "4", 'name' => "TT"],
            ['brand_id' => "4", 'name' => "TT RS"],
            ['brand_id' => "4", 'name' => "TTS"],

            ['brand_id' => "5", 'name' => "Arnage"],
            ['brand_id' => "5", 'name' => "Azure"],
            ['brand_id' => "5", 'name' => "Bentayga"],
            ['brand_id' => "5", 'name' => "Brooklands"],
            ['brand_id' => "5", 'name' => "Continental"],
            ['brand_id' => "5", 'name' => "Eight"],
            ['brand_id' => "5", 'name' => "Flying Spur"],
            ['brand_id' => "5", 'name' => "Mulsanne"],
            ['brand_id' => "5", 'name' => "Turbo R"],
            ['brand_id' => "5", 'name' => "Turbo RT"],
            ['brand_id' => "5", 'name' => "Turbo S"],

            ['brand_id' => "6", 'name' => "114"],
            ['brand_id' => "6", 'name' => "116"],
            ['brand_id' => "6", 'name' => "118"],
            ['brand_id' => "6", 'name' => "120"],
            ['brand_id' => "6", 'name' => "123"],
            ['brand_id' => "6", 'name' => "125"],
            ['brand_id' => "6", 'name' => "130"],
            ['brand_id' => "6", 'name' => "135"],
            ['brand_id' => "6", 'name' => "140"],
            ['brand_id' => "6", 'name' => "2002"],
            ['brand_id' => "6", 'name' => "214"],
            ['brand_id' => "6", 'name' => "216"],
            ['brand_id' => "6", 'name' => "218"],
            ['brand_id' => "6", 'name' => "220"],
            ['brand_id' => "6", 'name' => "225"],
            ['brand_id' => "6", 'name' => "228"],
            ['brand_id' => "6", 'name' => "230"],
            ['brand_id' => "6", 'name' => "235"],
            ['brand_id' => "6", 'name' => "240"],
            ['brand_id' => "6", 'name' => "315"],
            ['brand_id' => "6", 'name' => "316"],
            ['brand_id' => "6", 'name' => "318"],
            ['brand_id' => "6", 'name' => "320"],
            ['brand_id' => "6", 'name' => "323"],
            ['brand_id' => "6", 'name' => "324"],
            ['brand_id' => "6", 'name' => "325"],
            ['brand_id' => "6", 'name' => "328"],
            ['brand_id' => "6", 'name' => "330"],
            ['brand_id' => "6", 'name' => "335"],
            ['brand_id' => "6", 'name' => "340"],
            ['brand_id' => "6", 'name' => "418"],
            ['brand_id' => "6", 'name' => "420"],
            ['brand_id' => "6", 'name' => "425"],
            ['brand_id' => "6", 'name' => "428"],
            ['brand_id' => "6", 'name' => "430"],
            ['brand_id' => "6", 'name' => "435"],
            ['brand_id' => "6", 'name' => "440"],
            ['brand_id' => "6", 'name' => "518"],
            ['brand_id' => "6", 'name' => "520"],
            ['brand_id' => "6", 'name' => "523"],
            ['brand_id' => "6", 'name' => "524"],
            ['brand_id' => "6", 'name' => "525"],
            ['brand_id' => "6", 'name' => "528"],
            ['brand_id' => "6", 'name' => "530"],
            ['brand_id' => "6", 'name' => "535"],
            ['brand_id' => "6", 'name' => "540"],
            ['brand_id' => "6", 'name' => "545"],
            ['brand_id' => "6", 'name' => "550"],
            ['brand_id' => "6", 'name' => "628"],
            ['brand_id' => "6", 'name' => "630"],
            ['brand_id' => "6", 'name' => "633"],
            ['brand_id' => "6", 'name' => "635"],
            ['brand_id' => "6", 'name' => "640"],
            ['brand_id' => "6", 'name' => "645"],
            ['brand_id' => "6", 'name' => "650"],
            ['brand_id' => "6", 'name' => "725"],
            ['brand_id' => "6", 'name' => "728"],
            ['brand_id' => "6", 'name' => "730"],
            ['brand_id' => "6", 'name' => "732"],
            ['brand_id' => "6", 'name' => "735"],
            ['brand_id' => "6", 'name' => "740"],
            ['brand_id' => "6", 'name' => "745"],
            ['brand_id' => "6", 'name' => "750"],
            ['brand_id' => "6", 'name' => "760"],
            ['brand_id' => "6", 'name' => "830"],
            ['brand_id' => "6", 'name' => "840"],
            ['brand_id' => "6", 'name' => "850"],
            ['brand_id' => "6", 'name' => "i3"],
            ['brand_id' => "6", 'name' => "i8"],
            ['brand_id' => "6", 'name' => "1 M Coup\xC3\xA9"],
            ['brand_id' => "6", 'name' => "M2"],
            ['brand_id' => "6", 'name' => "M3"],
            ['brand_id' => "6", 'name' => "M4"],
            ['brand_id' => "6", 'name' => "M5"],
            ['brand_id' => "6", 'name' => "M6"],
            ['brand_id' => "6", 'name' => "X1"],
            ['brand_id' => "6", 'name' => "X3"],
            ['brand_id' => "6", 'name' => "X4"],
            ['brand_id' => "6", 'name' => "X4 M"],
            ['brand_id' => "6", 'name' => "X5"],
            ['brand_id' => "6", 'name' => "X5 M"],
            ['brand_id' => "6", 'name' => "X6"],
            ['brand_id' => "6", 'name' => "X6 M"],
            ['brand_id' => "6", 'name' => "Z1"],
            ['brand_id' => "6", 'name' => "Z3"],
            ['brand_id' => "6", 'name' => "Z3 M"],
            ['brand_id' => "6", 'name' => "Z4"],
            ['brand_id' => "6", 'name' => "Z4 M"],
            ['brand_id' => "6", 'name' => "Z8"],
            /*
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                      ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        ['brand_id' => "5", 'name' => "Arnage"],
                        /*['name' => "BMW"],
                        ['name' => "Chevrolet"],
                        ['name' => "Citro\xC3\xABn"],
                        ['name' => "Dacia"],
                        ['name' => "Dodge"],
                        ['name' => "DS"],
                        ['name' => "Ferrari"],
                        ['name' => "Fiat"],
                        ['name' => "Ford"],
                        ['name' => "Honda"],
                        ['name' => "Hyundai"],
                        ['name' => "Infiniti"],
                        ['name' => "Jaguar"],
                        ['name' => "Jeep"],
                        ['name' => "KIA"],
                        ['name' => "Lada"],
                        ['name' => "Lamborghini"],
                        ['name' => "Lancia"],
                        ['name' => "Land Rover"],
                        ['name' => "Lexus"],
                        ['name' => "Lotus"],
                        ['name' => "Maserati"],
                        ['name' => "Mazda"],
                        ['name' => "McLaren"],
                        ['name' => "Mercedes-Benz"],
                        ['name' => "Mia Electric"],
                        ['name' => "MINI"],
                        ['name' => "Mitsubishi"],
                        ['name' => "Nissan"],
                        ['name' => "Opel"],
                        ['name' => "Peugeot"],
                        ['name' => "Porsche"],
                        ['name' => "Renault"],
                        ['name' => "Rolls-Royce"],
                        ['name' => "Saab"],
                        ['name' => "Seat"],
                        ['name' => "Skoda"],
                        ['name' => "Smart"],
                        ['name' => "Ssangyong"],
                        ['name' => "Subaru"],
                        ['name' => "Suzuki"],
                        ['name' => "Tesla"],
                        ['name' => "Toyota"],
                        ['name' => "Volkswagen"],
                        ['name' => "Volvo"]*/
        ]);
    }
}